pipeline {
    agent any

    tools {
        maven 'Maven-3.9'
    }

    environment {
        APP_NAME   = "employee-service"
        IMAGE_NAME = "arindamtiwari/employee-service"
       // IMAGE_TAG  = "${BUILD_NUMBER}"
        APP_PORT   = "8081"
        SONARQUBE_SERVER = "SonarQube"
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build') {
            steps {
                dir('application/employee-service') {
                    sh 'mvn clean package'
                }
            }
        }

        stage('SonarQube Analysis') {
            steps {

                withSonarQubeEnv("${SONARQUBE_SERVER}") {

                    dir('application/employee-service') {

                        sh '''
                            mvn clean verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
                        '''

                    }
                }
            }
        }

        stage('Quality Gate') {

            steps {

                timeout(time: 5, unit: 'MINUTES') {

                    waitForQualityGate abortPipeline: true

                }

            }

        }

        stage('Archive Artifact') {
            steps {
                archiveArtifacts artifacts: 'application/employee-service/target/*.jar', fingerprint: true
            }
        }

 /*      stage('Debug') {
            steps {
                echo "BUILD_NUMBER = ${env.BUILD_NUMBER}"
                echo "IMAGE_NAME   = ${IMAGE_NAME}"
            }
        } */

        stage('Build Docker Image') {
            steps {
                dir('application/employee-service') {
                    sh """
                        docker build -t ${IMAGE_NAME}:${env.BUILD_NUMBER} .
                        docker tag ${IMAGE_NAME}:${env.BUILD_NUMBER} ${IMAGE_NAME}:latest
                    """
                }
            }
        }

        stage('Docker Push') {
            steps {

                withCredentials([
                    usernamePassword(
                        credentialsId: 'dockerhub-creds',
                        usernameVariable: 'DOCKER_USER',
                        passwordVariable: 'DOCKER_PASS'
                    )
                ]) {

                    sh """
                        echo "\$DOCKER_PASS" | docker login -u "\$DOCKER_USER" --password-stdin
                        docker push ${IMAGE_NAME}:${env.BUILD_NUMBER}
                        docker push ${IMAGE_NAME}:latest
                        docker logout
                    """
                }
            }
        }

  /*      stage('Deploy Container') {
            steps {
                sh """
                    docker stop employee-service || true
                    docker rm -f employee-service || true

                    docker run -d \
                    --name employee-service \
                    --restart unless-stopped \
                    --network employee-service_default \
                    -p 8081:8081 \
                    -e SPRING_DATASOURCE_URL=jdbc:mysql://employee-mysql:3306/employee_db \
                    -e SPRING_DATASOURCE_USERNAME=root \
                    -e SPRING_DATASOURCE_PASSWORD=root \
                    ${IMAGE_NAME}:${env.BUILD_NUMBER}
                """
            }
        }  */

        stage('Deploy Container') {

            steps {

                dir('deployment') {

                    withEnv([
                        "IMAGE_NAME=${IMAGE_NAME}:latest"
                    ]) {

                        sh '''
                            docker compose down || true
                            docker compose pull
                            docker compose up -d
                        '''
                    }
                }
            }
        }

        stage('Health Check') {
            steps {
                sh '''
                    echo "========================================"
                    echo "Starting Health Check..."
                    echo "========================================"

                    MAX_RETRIES=12
                    RETRY_INTERVAL=5
                    COUNT=1

                    while [ $COUNT -le $MAX_RETRIES ]
                    do
                        echo ""
                        echo "Attempt $COUNT of $MAX_RETRIES"

                        if docker exec employee-service \
                            wget -q --spider http://localhost:8081/actuator/health
                        then
                            echo ""
                            echo "Application is Healthy"
                            docker exec employee-service \
                                wget -qO- http://localhost:8081/actuator/health
                            exit 0
                        fi

                        echo "Application not ready..."
                        sleep $RETRY_INTERVAL

                        COUNT=$((COUNT+1))
                    done

                    echo ""
                    echo "Health Check Failed"

                    echo ""
                    echo "========= Container Logs ========="
                    docker logs employee-service

                    exit 1
                '''
            }
        }

        stage('Smoke Test') {
            steps {
                sh """
                    EMAIL="arindam${env.BUILD_NUMBER}@gmail.com"

                    echo "Creating Employee..."

                    docker run --rm \
                        --network deployment_employee-network \
                        curlimages/curl:latest \
                        -s \
                        -X POST \
                        http://employee-service:8081/employees \
                        -H "Content-Type: application/json" \
                        -d '{
                            "firstName":"Arindam",
                            "lastName":"Tiwari",
                            "email":"'"\$EMAIL"'",
                            "department":"DevOps",
                            "salary":90000
                        }'

                    echo ""
                    echo "Verifying Employee..."

                    docker run --rm \
                        --network deployment_employee-network \
                        curlimages/curl:latest \
                        -s \
                        http://employee-service:8081/employees \
                        > employees.json

                    cat employees.json

                    grep "\$EMAIL" employees.json

                    echo ""
                    echo "Smoke Test Passed"
                """
            }
        }

        stage('Deployment Summary') {
            steps {
                script {
                    sh """
                        echo ""
                        echo "==============================================================="
                        echo "                 DEPLOYMENT SUMMARY"
                        echo "==============================================================="
                        echo " Application Name : ${APP_NAME}"
                        echo " Docker Image     : ${IMAGE_NAME}:${env.BUILD_NUMBER}"
                        echo " Container Name   : employee-service"
                        echo ""
                        echo " Application URL  : http://localhost:${APP_PORT}/employees"
                        echo " Health URL       : http://localhost:${APP_PORT}/actuator/health"
                        echo " Info URL         : http://localhost:${APP_PORT}/actuator/info"
                        echo ""
                        echo " Build Number     : ${env.BUILD_NUMBER}"
                        echo " Jenkins Job      : ${JOB_NAME}"
                        echo " Build URL        : ${BUILD_URL}"
                        echo ""
                        echo " Status           : DEPLOYMENT SUCCESSFUL"
                        echo "==============================================================="
                    """
                }
            }
        }

   /*     stage('Health Check') {
            steps {
                sh '''
                    echo "Waiting for application to start..."
                    sleep 20

                    echo "Running Health Check..."

                   # curl -f http://employee-service:8081/employees
                   # curl -f  http://localhost:8081/employees


                '''
            }
        }

        stage('Smoke Test') {
            steps {
                sh '''
                    echo "Running Smoke Test..."

                    curl -X POST http://localhost:8081/employees \
                    -H "Content-Type: application/json" \
                    -d '{
                        "firstName":"Arindam",
                        "lastName":"Tiwari",
                        "email":"arindam@example.com",
                        "department":"IT",
                        "salary":90000
                    }'

                    echo ""
                    echo "Verifying inserted employee..."

                    curl -f http://employee-service:8081/employees

                    echo ""
                    echo "Smoke Test Passed"
                '''
            }
        }  */

        stage('Verify Deployment') {
            steps {
                sh '''
                    sleep 20

                    docker ps

                    docker logs employee-service --tail 50
                '''
            }
        }

        stage('Docker Cleanup') {
            steps {
                sh """
                    echo "Cleaning Docker..."

                    docker image prune -af --filter "until=48h"
                    # docker image prune -f
                    # docker builder prune -f

                    echo "Docker Cleanup Completed."
                """
            }
        }

   /*     stage('List Docker Images') {
            steps {
                sh 'docker images'
            }
        } */
    } 

    post {
        success {
            echo 'Pipeline completed successfully.'
        }

        failure {
            echo 'Pipeline failed.'
        }
    }
}